### DISCUSSION TITLE
prowler dashboard

### DISCUSSION THREAD

**Discussion by keerthanap0810** [prowler-cloud/prowler#3955] [Q&A] [answered]
i was trying to run prowler dashbaord in k8
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod  
spec:
  containers:
    - name: dash
      image: toniblyx/prowler:stable
      args: ["dashboard"]
      ports:
        - containerPort: 11666

---

apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: test-pod  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11666
  type: LoadBalancer
```
I'm unable to access the dashboard outside the eks cluster, meaning port forwarding works but not able to call from another pod or  from loadbalancer dns
