### DISCUSSION TITLE
Strange behaviors with wildcards in Mutelists

### DISCUSSION THREAD

**Discussion by F30** [prowler-cloud/prowler#7544] [Q&A] [answered]
Consider the following Mutelist for AWS:

```yaml
Mutelist:
  Accounts:
    "*":
      Checks:
        "cloudtrail_*":
          Regions: ["*"]
          Resources: ["*"]
```

As far as I understand, it should mute all checks whose name starts with "cloudtrail_". (The wording is a bit ambiguous here – the [docs](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/mutelist/) call it `check_name` or just "check", the web UI "Check ID". I assume they're all the same.)

However,  with this Mutelist, the check "iam_inline_policy_no_full_access_to_cloudtrail" does show up as muted. It clearly does not match the pattern. Its title contains the string "cloudtrail:*", which looks similar, but doesn't really match either.

Now, look at this Mutelist:

```yaml
Mutelist:
  Accounts:
    "*":
      Checks:
        "guardduty_*_enabled":
          Regions: ["*"]
          Resources: ["*"]

```

From my understanding, it should mute (among others) the "guardduty_is_enabled" check. But in this case, the check does **not** get muted.

Are these behaviors desired behavior or bugs? What am I missing?
